### ISSUE TITLE
we never mentioned `for` loops

### ISSUE THREAD

**Issue by loganhasson** [learn-co-curriculum/iterators-and-abstraction-ruby#11]
do we want to mention them in the curriculum? or just take out the mention of them here?

**Comment by jmburges** [comment]
Yes we do, which track are you using?

**Comment by loganhasson** [comment]
qualifying track. we definitely don't talk about them.

**Comment by loganhasson** [comment]
(Intro to Ruby Web Development)

**Comment by AnnJohn** [comment]
took out the mention of `for` loops
