### ISSUE TITLE
Are these example methods wrong? 

### ISSUE THREAD

**Issue by fullstack212** [learn-co-curriculum/iterators-and-abstraction-ruby#16]
Wouldn't this example method stop removing apples from the basket when there were 5 apples in the basket and 5 taken out instead of continuing until all the apples were removed from the basket?  Because at that point the condition for continuing to iterate would be false---5 is not less than 5.  Or am I just misunderstanding something?  Thanks! 

basket = ["apple 1","apple 2","apple 3","apple 4","apple 5","apple 6","apple 7","apple 8","apple 9","apple 10"]

apples_in_basket = basket.size # Step 1
apples_taken_out = 0 # Step 2

loop do # Step 3
    if apples_taken_out < apples_in_basket 
        # Step 4
        puts "Taking out #{basket[apples_taken_out]}"
        apples_taken_out += 1
    else
        # Step 5
        break
    end
end

**Comment by AnnJohn** [comment]
Hi @fullstack212 sorry for the delay on this. If you still have questions on this or any other lab, use the Ask a Question tool in Learn and someone from our Learn support team will get back to you. Thanks!
