### ISSUE TITLE
For loop 

### ISSUE THREAD

**Issue by tttra** [learn-co-curriculum/iterators-and-abstraction-ruby#21]
In the first paragraph of the Interation vs. Looping section, it states: "In previous readings we discussed the five loop types, loop, times, while, until, and for."

However, I can't find information about for loop in the preceeding lessons. I'd appreciate more information on this part. 

Thanks!

**Comment by AnnJohn** [comment]
Hi @tttra yes, we didn't cover `for` loops and that was a typo on our part. We removed it from the lesson here. Thanks!
