### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ryecox** [learn-co-curriculum/iterators-and-abstraction-ruby#23]
Was given a banner message at the top (in red) that stated, "You do not have access to this lesson." 
This didn't appear until I was accepted and paid for the program. Aside from that, everything seems to be working.

**Comment by AnnJohn** [comment]
hi @ryecox sorry for the issue. If this is still a problem and since this is a technical issue, could you file a bug report? If you hover over your profile pic in Learn, you'll see an option to do so. We use this space for issues specifically related to the content within the lessons. Thanks!
