### ISSUE TITLE
Removing apples from basket example

### ISSUE THREAD

**Issue by tostonar** [learn-co-curriculum/iterators-and-abstraction-ruby#25]
If the goal is to remove all of the 10 apples from the basket, and you're using:
```ruby
basket = ["apple 1","apple 2","apple 3","apple 4","apple 5","apple 6","apple 7","apple 8","apple 9","apple 10"]
 
apples_in_basket = basket.size # Step 1
apples_taken_out = 0 # Step 2
 
# Step 3 + 4
while apples_taken_out < apples_in_basket
    puts "Taking out #{basket[apples_taken_out]}"
    apples_taken_out += 1
end
```
Wouldn't the loop stop when 5 apples are taken out? What am I missing here?

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by tostonar** [comment]
Actually, nevermind. I see that apples_taken_out changes with each loop, but that apples_in_basket doesn't change. It was set to 10, and stays that way. My bad.
