### ISSUE TITLE
more clarity 

### ISSUE THREAD

**Issue by gbs4ever** [learn-co-curriculum/iterators-and-abstraction-ruby#28]
In this lesson it is trying to teach us  how to code more abstractly , however the two  examples are not totally equal , For a beginner (like myself) the two  examples should do the same thing but written differently. however in this case the 1st example only lets you empty half the basket 

```ruby
basket = ["apple 1","apple 2","apple 3","apple 4","apple 5","apple 6","apple 7","apple 8","apple 9","apple 10"]
 
apples_in_basket = basket.size 
apples_taken_out = 0 # Step 2
 
while apples_taken_out < apples_in_basket
    puts "Taking out #{basket[apples_taken_out]}"
    apples_taken_out += 1
end
# the while statement will close/stop at the half way point
```

**In the more abstract we can empty the whole basket** 

```ruby
basket.each do |apple|
    puts "Taking out #{apple}"
end
```

Thank you 
sim

**Comment by sgharms** [comment]
@gbs4ever 

I'm a bit confused by your comment:

`# the while statement will close/stop at the half way point`

On my read of the logic, that's incorrect. It **will** iterate through all the elements and end with `apples_taken_out === basket.size`.

```ruby
basket = ["apple 1","apple 2","apple 3","apple 4","apple 5","apple 6","apple 7","apple 8","apple 9","apple 10"]

apples_in_basket = basket.size
apples_taken_out = 0 # Step 2

while apples_taken_out < apples_in_basket
    puts "Taking out #{basket[apples_taken_out]}"
    apples_taken_out += 1
end

raise("You didn't take out the right number of apples") if apples_in_basket != apples_in_basket
```

Question: Did I miss some detail here?

In general, I think you're right, we should keep the abstraction level similar. By that logic I propose that:

The measurable change in the while loop is that `apples_taken_out` increments until it matches `basket.size`. Therefore, the main work of the `each` block should be to do the same thing. Ergo:

```ruby
basket.each do |apple|
    puts "Taking out #{apple}"
    apples_taken_out += 1
end
```

If that addresses your concern, please let me know and I'll merge the change.

**Comment by gbs4ever** [comment]
you are right !  My mistake I  see  apples_in_basket  never changes an remains = 10 the whole time. Your new code does clarify that point ;that the 2 methods are the same just one is abstract . 


All the best 
Sim

**Comment by sgharms** [comment]
@gbs4ever Change has been committed. Thank you for your insight.
