### ISSUE TITLE
Small error in code snippet

### ISSUE THREAD

**Issue by GCdM** [learn-co-curriculum/iterators-and-abstraction-ruby#29]
In the code snippet explaining the `each` iterator, the variable `apples_taken_out` is undeclared

**Comment by drakeltheryuujin** [comment]
Hi @GCdM,

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
