### ISSUE TITLE
each - The Most Abstract Code Errors in the lecture 

### ISSUE THREAD

**Issue by namdevlife** [learn-co-curriculum/iterators-and-abstraction-ruby#30]
This code is giving me errors and it is part of the lecture. Should this code be tested before being posted in the lecture ? Because this will cause the confusion for the beginners. 

basket = ["apple 1","apple 2","apple 3","apple 4","apple 5","apple 6","apple 7","apple 8","apple 9","apple 10"]
 
# Step 1,2,3,4,5 as one, abstractly
basket.each do |apple|
  puts "Taking out #{apple}"
  apples_taken_out += 1
end

Here is the Error message

ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
   
Taking out apple 1
undefined method `+' for nil:NilClass
(repl):6:in `block in <main>'
(repl):4:in `each'
(repl):4:in `<main>'

**Comment by drakeltheryuujin** [comment]
Hi @namdevlife,

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
