### ISSUE TITLE
the most abstract errors

### ISSUE THREAD

**Issue by AD0791** [learn-co-curriculum/iterators-and-abstraction-ruby#31]
basket = ["apple 1","apple 2","apple 3","apple 4","apple 5","apple 6","apple 7","apple 8","apple 9","apple 10"]
 
# Step 1,2,3,4,5 as one, abstractly
basket.each do |apple|
  puts "Taking out #{apple}"
end

that's the correct implementation!

**Comment by drakeltheryuujin** [comment]
Hi @AD0791,

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
