### ISSUE TITLE
#5 bullet point

### ISSUE THREAD

**Issue by mcavaioni** [learn-co-curriculum/iterators-and-abstraction-ruby#8]
the Bullet point #5 in LOOP_LEAST ABSTRACT says:
If the count of apples taken out is LESS than to the count of apples originally in the basket, then break out of the loop.

it should say:
If the count of apples taken out is MORE than to the count of apples originally in the basket, then break out of the loop.

**Comment by AnnJohn** [comment]
Thanks @mcavaioni for raising this issue. We're reviewing and updating our curriculum now, and so will put this on icebox for now and will "thaw" it out once we get to this specific lesson.

**Comment by SophieDeBenedetto** [comment]
thanks @mcavaioni. fixed!
